[project]
name = "pandora"
version = "0.1.0"
description = "A mental health chatbot powered by AI."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.120.0",
    "openai>=2.6.0",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
]
